version: '3'
services:
  api:
    build: .
    depends_on:
      - elastic
    ports:
      - "9876:9876"
    environment:
      ELASTIC_CONN: elastic:9200
      ALLOW_ORIGIN: http://localhost:3000
      #FLASK_ENV: development
    command: webapi
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.7"
    ports:
      - "9200:9200"
    volumes:
      - $PWD/data:/usr/share/elasticsearch/data:Z
  crawler:
    build: .
    depends_on:
      - elastic
    command: monocle --elastic-conn elastic:9200 crawler --config /etc/projects.yaml
    volumes:
      - $PWD/etc:/etc:Z
      - $PWD/dump:/var/lib/crawler:Z
  web:
    build: web
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:9876
