name: Haskell
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Haskell GHC
    container:
      image: quay.io/change-metrics/builder
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ln -s /root/.cabal /github/home/.cabal
      - run: cd haskell; cabal build --enable-tests all
      - run: cd haskell; cabal test --test-show-details=direct test:monocle-test test:monocle-doctest
