name: Haskell
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Haskell GHC
    container:
      image: quay.io/change-metrics/builder
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ln -s /root/.cabal /github/home/.cabal
      - run: cd haskell; cabal build --enable-tests --flags=ci all
      - run: cd haskell; cabal test --test-show-details=direct test:monocle-test test:monocle-doctest
# This adds quite a bit of build time and this should be using the pre build container
#      - run: cabal v2-install stan --install-method=copy --overwrite-policy=always
#      - run: cd haskell; ~/.cabal/bin/stan report || true
#      - uses: actions/upload-artifact@v2
#        with:
#          name: stan-report
#          path: ./haskell/stan.html
