on:
  push:
    branches:
      - master

jobs:
  publish-master:
    if: github.repository_owner == 'change-metrics'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Build docker images
        run: |
          ln -s docker-compose.yml.dev docker-compose.yml
          docker-compose build

      - name: Set write permission for others for data directory
        run: |
          chmod o+w data

      - name: Create a config.yaml file
        run: |
          cat > etc/config.yaml << EOL
          ---
          tenants:
            - index: monocle
              crawlers_api_key: "CHANGE_ME"
              crawlers:
                - name: github-tekton
                  update_since: "2020-01-01"
                  provider:
                    github_token: "123"
                    github_organization: tekton
          EOL

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 15

      - name: Display docker-compose ps
        run: docker-compose ps; docker-compose logs

      - name: Check elastic service
        run: docker-compose ps elastic | grep Up

      - name: Check api service
        run: |
          docker-compose ps api | grep Up
          curl -s http://localhost:9876/api/0/indices

      - name: Check api-ng server
        run: docker-compose logs api-ng

      - name: Check web server
        run: docker-compose logs web

      - name: Check crawler service
        run: docker-compose ps crawler | grep Up

      - name: Check web service
        run: |
          docker-compose ps web | grep Up
          curl -s http://localhost:8080/

      - name: Publish images to quay.io
        run: |
          docker login -u "${{ secrets.QUAYIO_USERNAME }}" -p "${{ secrets.QUAYIO_PASSWORD }}" quay.io
          set -x
          docker tag monocle_web:latest quay.io/change-metrics/monocle_web:latest
          docker push quay.io/change-metrics/monocle_web:latest
          docker tag monocle_api:latest quay.io/change-metrics/monocle_backend:latest
          docker push quay.io/change-metrics/monocle_backend:latest
          docker tag monocle_api-ng:latest quay.io/change-metrics/monocle_api:latest
          docker push quay.io/change-metrics/monocle_api:latest
