on:
  push:
    branches:
      - master

jobs:
  publish-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      
      - name: Build docker images
        run: |
          ln -s docker-compose.yml.dev docker-compose.yml
          docker-compose up -d --build

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: |
          tox
          curl -s http://localhost:3000/

      - name: Publish images to docker-hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          set -x
          docker tag monocle_web:latest changemetrics/monocle_web:latest
          docker push changemetrics/monocle_web:latest
          docker tag monocle_api:latest changemetrics/monocle_backend:latest
          docker push changemetrics/monocle_backend:latest
