env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
ignorePatterns: "**/*.bs.js"
rules:
  # See: https://github.com/facebook/react/issues/15227
  react-hooks/rules-of-hooks: 0
  prettier/prettier:
    - error
    - usePrettierrc: true
settings:
  react:
    # Regex for Component Factory to use,
    # default to "createReactClass"
    createClass: createReactClass
    # Pragma to use, default to "React"
    pragma: React
    version: detect
  # The names of any function used to wrap propTypes,
  # e.g. `forbidExtraProps`. If this isn't set, any propTypes wrapped
  # in a function will be skipped.
  propWrapperFunctions:
    - forbidExtraProps
    - property: freeze
      object: Object
    - property: myFavoriteWrapper
  # Components used as alternatives to <a> for linking, eg. <Link to={ url } />
  linkComponents:
    - Hyperlink
    - name: Link
      linkAttribute: to
